### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [mlampros/fitbitViz#6]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by mlampros** [comment]
@rsbivand thank you for the reminder, now I see in this second blog post [https://r-spatial.org/r/2022/12/14/evolution2.html](https://r-spatial.org/r/2022/12/14/evolution2.html)

```
... This also means that all packages that depend on or import from raster, and added a weak dependency 
on rgdal and rgeos for that reason, may now drop those dependencies, conditional on requiring raster
of version >= 3.6-3 ...
```
The main reason that I included 'rgdal' in the DESCRIPTION file was due to the fact that it was a dependency of raster.
I'll do the changes in the next days.
